l_english:
 CK2DISPLAYNAME: "Crusader Kings II to Europa Universalis IV"
 EU4DISPLAYNAME: "Europa Universalis IV to Victoria II"
 VIC2DISPLAYNAME: "Victoria II to Hearts of Iron IV"
 CK2GAME: "Crusader Kings II"
 EU4GAME: "Europa Universalis IV"
 VIC2GAME: "Victoria II"
 HOI4GAME: "Hearts of Iron IV"
 CK2FOLDER: "Crusader Kings II Install Directory"
 CK2FOLDERTIP: "The path on your computer where Crusader Kings II is installed"
 CK2MOD: "Crusader Kings II Mod Directory"
 CK2MODTIP: "The path on your computer where Crusader Kings II stores mods"
 EU4FOLDER: "Europa Universalis IV Install Directory"
 EU4FOLDERTIP: "The path on your computer where Europa Universalis IV is installed"
 EU4MOD: "Europa Universalis IV Steam Workshop Directory"
 EU4MODTIP: "The path on your computer where Europa Universalis IV stores Steam mods"
 VIC2FOLDER: "Victoria II Install Directory"
 VIC2FOLDERTIP: "The path on your computer where Victoria II is installed"
 VIC2MOD: "Victoria II Mod Directory"
 VIC2MODTIP: "The path on your computer where Victoria II stores mods"
 HOI4FOLDER: "Hearts of Iron IV Install Directory"
 HOI4FOLDERTIP: "The path on your computer where Hearts of Iron IV is installed"
 HOI4MOD: "Hearts of Iron IV Mod Directory"
 HOI4MODTIP: "The path on your computer where Hearts of Iron IV stores mods"
 CK2FILE: "Path to the converter executable"
 CK2FILETIP: "Path to CK2ToEU4Converter.exe"
 CK2SAVE: "Path to the CK2 savegame"
 CK2SAVETIP: "Path to your savegame from CK2"
 EU4FILE: "Path to the converter executable"
 EU4FILETIP: "Path to EU4ToVic2Converter.exe"
 EU4SAVE: "Path to the EU4 savegame"
 EU4SAVETIP: "Path to your savegame from EU4"
 VIC2FILE: "Path to the converter executable"
 VIC2FILETIP: "Path to Vic2ToHoI4Converter.exe"
 VIC2SAVE: "Path to the Vic2 savegame"
 VIC2SAVETIP: "Path to your savegame from Vic2"
 EU4DOC: "Europa Universalis IV Documents Directory"
 EU4DOCTIP: "A path on your computer where Europa Universalis IV keeps temporary files"
 CK2EXP: "(Optional) Crusader Kings II Export Directory"
 CK2EXPTIP: "(Optional) A path on your computer where Crusader Kings II keeps exported games"
 VIC2DOC: "Victoria II Documents Directory"
 VIC2DOCTIP: "A path on your computer where Victoria II keeps temporary files"